.PHONY: setup-dev build-dev run-dev hf sf ff


run-dev:
	cmake --preset=dev-linux .
	mv build/dev/compile_commands.json ./
	cmake --build build/dev
	@./build/dev/cfd $(PWD)

hf:
	@./scripts/create_file.sh h

sf:
	@./scripts/create_file.sh s

ff:
	@./scripts/create_file.sh f